version: '3.8'

services:
  server:
    build: ./
    command: ./market
    ports:
      - "8082:8082"
      - "8080:8080"
    restart: always
    depends_on:
      - mongo
      - prometheus
  
  mongo:
    image: mongo:latest
    restart: always
    ports:
      - "27017:27017"
    
  prometheus:
    image: prom/prometheus:latest
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "19090:9090"
