version: '3.8'

services:
  server:
    build: ./
    command: ./market
    ports:
      - "8080:8080"
    restart: always
    depends_on:
      - mongo
  
  mongo:
    image: mongo:latest
    restart: always
    ports:
      - "27017:27017"
